version: '3.8'

services:
  web-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ${DATA_DIR:-./data}:/data
    environment:
      - DATADIR=/data
    container_name: deepchem_server
