services:
  deepchem-server:
    image: deepchem-server
    container_name: deepchem-server
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - "8000:8000"
    restart: always
    environment:
      - AWS_BUCKET=${AWS_BUCKET:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_BATCH_CPU_JOB_QUEUE=${AWS_BATCH_CPU_JOB_QUEUE:-}
      - AWS_BATCH_GPU_JOB_QUEUE=${AWS_BATCH_GPU_JOB_QUEUE:-}
      - AWS_BATCH_CPU_JOB_DEFINITION=${AWS_BATCH_CPU_JOB_DEFINITION:-}
      - AWS_BATCH_GPU_JOB_DEFINITION=${AWS_BATCH_GPU_JOB_DEFINITION:-}