FROM mambaorg/micromamba:2.3.2

ARG DEEPCHEM_SERVER_HOME=/opt/deepchem_server_app
ARG MAMBA_USER=mambauser

ENV DEEPCHEM_SERVER_HOME=${DEEPCHEM_SERVER_HOME} \
    MAMBA_NO_LOW_SPEED_LIMIT=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    DEBIAN_FRONTEND=noninteractive

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    libgomp1 \
    libxrender1 \
    libxext6 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
USER $MAMBA_USER

WORKDIR ${DEEPCHEM_SERVER_HOME}

COPY --chown=$MAMBA_USER:$MAMBA_USER deepchem_server/environments/core_environment.yml /tmp/env.yaml

RUN micromamba install -y -n base -f /tmp/env.yaml && \
    micromamba clean --all --yes && \
    rm -f /tmp/env.yaml

COPY --chown=$MAMBA_USER:$MAMBA_USER . ${DEEPCHEM_SERVER_HOME}/

ENTRYPOINT ["python", "-m", "deepchem_server.aws.command"]
