name: Test pyds Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-pyds-library:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Make docker script executable
        run: chmod +x ./docker.sh

      - name: Run build and run script
        run: ./docker.sh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pyds library and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e "./pyds/[dev]"

      - name: Verify pyds installation
        run: |
          python --version
          pip list | grep pyds
          python -c "import sys; print('Python path:', sys.path)"
          python -c "import pyds; print(f'pyds version: {pyds.__version__}')"
          python -c "from pyds import Settings, Primitives, Data, BaseClient; print('All main classes imported successfully')"

      - name: Run tests
        run: |
          pytest pyds/tests/ -v --cov=pyds --cov-report=term-missing
